import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync,existsSync } from "node:fs";
const root=new URL("../",import.meta.url);const read=(p)=>readFileSync(new URL(p,root),"utf8");
const contracts=read("packages/agent-runtime/src/core/contracts.ts");
const bridgePath=new URL("apps/web/dev/bridges/agent/agent-runtime-bridge.ts",root);
const client=read("apps/web/src/host-clients/agent-runtime-client.ts");const app=read("apps/web/src/App.tsx");const workbench=read("packages/app-shell/src/AgentWorkbench.tsx");const chat=read("packages/workspace/src/chat/view/ChatWorkspace.tsx");const session=read("packages/workspace/src/shared/logic/useWorkspaceSessionController.ts");const composer=read("packages/app-shell/src/workbench/center/composer/view/ComposerRegion.tsx");const runtimeController=read("packages/app-shell/src/workbench/center/composer/runtime-control/logic/useRuntimeControlController.ts");const runtimeSurface=[workbench,chat,session,composer,runtimeController].join("\n");const vite=read("apps/web/vite.config.ts");

test("web development host exposes real model chat runtime",()=>{assert.equal(existsSync(bridgePath),true);const bridge=readFileSync(bridgePath,"utf8");for(const token of ["createWebDevSecretStore","credentialRef","/chat/completions","/responses","MAX_HISTORY_MESSAGES","assistant.completed"])assert.match(bridge,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.doesNotMatch(bridge,/console\.log\([^\n]*(?:credential|secret|Authorization)/i);assert.match(vite,/lfaaDevAgentRuntimeBridge\(projectRoot\)/);assert.match(app,/agentRuntimeHost=\{webAgentRuntimeHost\}/);});

test("AgentRuntimeHost maps runtime events into Chat view state",()=>{assert.match(contracts,/AgentRuntimeEvent/);assert.match(contracts,/subscribe\(listener: AgentRuntimeEventListener\)/);assert.match(client,/lfaa:agent-runtime-event/);assert.match(chat,/styles\.timeline/);assert.match(session,/assistant\.completed/);assert.match(session,/runtimeConnected:\s*Boolean\(runtimeHost\)/);assert.match(workbench,/runtimeConnected=\{session\.runtimeConnected\}/);});

test("strong reasoning travels as execution hint without inventing provider field",()=>{const bridge=readFileSync(bridgePath,"utf8");assert.match(contracts,/interface AgentExecutionHints/);assert.match(contracts,/executionHints\?: AgentExecutionHints/);assert.match(composer,/executionHints/);assert.match(runtimeController,/reasoningBoost: boostActive/);assert.match(bridge,/executionHints\?\.reasoningBoost|rawHints[\s\S]*reasoningBoost/);assert.match(bridge,/REASONING_BOOST_INSTRUCTION/);assert.match(bridge,/role: "system"/);assert.doesNotMatch(bridge,/reasoning_effort\s*:\s*request\.executionHints|reasoning\s*:\s*request\.executionHints/);});
