import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync,existsSync } from "node:fs";
const root=new URL("../",import.meta.url);const read=(p)=>readFileSync(new URL(p,root),"utf8");
const contracts=read("packages/core/agent-runtime/src/core/contracts.ts");
const bridgePath=new URL("packages/api/agent-controller/src/agent-runtime-bridge.ts",root);const llmPath=new URL("packages/llm/openai-compatible/src/index.ts",root);
const client=read("packages/client/connection/src/agent-runtime-client.ts");const app=read("packages/client/web/src/App.tsx");const workbench=read("packages/client/app-shell/src/AgentWorkbench.tsx");const chat=read("packages/client/workspace/src/chat/view/ChatWorkspace.tsx");const session=read("packages/client/workspace/src/shared/logic/useWorkspaceSessionController.ts");const composer=read("packages/client/app-shell/src/workbench/center/composer/view/ComposerRegion.tsx");const runtimeController=read("packages/client/app-shell/src/workbench/center/composer/runtime-control/logic/useRuntimeControlController.ts");const runtimeSurface=[workbench,chat,session,composer,runtimeController].join("\n");const vite=read("apps/web/vite.config.ts");const bundleVite=read("packages/bundle/web-app/src/vite.ts");

test("web development host exposes real model chat runtime",()=>{assert.equal(existsSync(bridgePath),true);assert.equal(existsSync(llmPath),true);const bridge=readFileSync(bridgePath,"utf8");const llm=readFileSync(llmPath,"utf8");for(const token of ["createWebDevSecretStore","credentialRef","MAX_HISTORY_MESSAGES","assistant.completed","callOpenAiCompatibleTextModel"])assert.match(bridge,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));for(const token of ["/chat/completions","/responses","REASONING_BOOST_INSTRUCTION","role: \"system\""])assert.match(llm,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.doesNotMatch(bridge,/console\.log\([^\n]*(?:credential|secret|Authorization)/i);assert.doesNotMatch(llm,/console\.log\([^\n]*(?:credential|secret|Authorization)/i);assert.match(vite,/@lfaa\/bundle-web-app\/vite/);assert.match(bundleVite,/lfaaDevAgentRuntimeBridge\(options\.projectRoot\)/);assert.match(app,/agentRuntimeHost=\{webAgentRuntimeHost\}/);});

test("AgentRuntimeHost maps runtime events into Chat view state",()=>{assert.match(contracts,/AgentRuntimeEvent/);assert.match(contracts,/subscribe\(listener: AgentRuntimeEventListener\)/);assert.match(client,/lfaa:agent-runtime-event/);assert.match(chat,/styles\.timeline/);assert.match(session,/assistant\.completed/);assert.match(session,/runtimeConnected:\s*Boolean\(runtimeHost\)/);assert.match(workbench,/runtimeConnected=\{session\.runtimeConnected\}/);});

test("strong reasoning travels as execution hint without inventing provider field",()=>{const bridge=readFileSync(bridgePath,"utf8");assert.match(contracts,/interface AgentExecutionHints/);assert.match(contracts,/executionHints\?: AgentExecutionHints/);assert.match(composer,/executionHints/);assert.match(runtimeController,/reasoningBoost: boostActive/);assert.match(bridge,/executionHints\?\.reasoningBoost|rawHints[\s\S]*reasoningBoost/);const llm=readFileSync(llmPath,"utf8");assert.match(llm,/REASONING_BOOST_INSTRUCTION/);assert.match(llm,/role: "system"/);assert.doesNotMatch(llm,/reasoning_effort\s*:\s*options\.request\.executionHints|reasoning\s*:\s*options\.request\.executionHints/);});
