/** Settings 页面壳。Host/controller 数据通过 props 注入，不读取 Workbench 兄弟模块状态。 */
import type { ThemePreference } from "@lfaa/ui";
import type { SettingsSectionId } from "../contracts/settings.types";
import { SettingsPage } from "./SettingsPage";
import type { AiSettingsController } from "../logic/useAiSettingsController";
import type { PluginSettingsController } from "../logic/usePluginSettingsController";
import styles from "../styles/SettingsSurface.module.css";
export function SettingsSurface({activeSection,onSectionChange,onClose,leftPaneWidth,onLeftPaneWidthChange,themePreference,onThemePreferenceChange,ai,plugins}:{activeSection:SettingsSectionId;onSectionChange:(section:SettingsSectionId)=>void;onClose:()=>void;leftPaneWidth:number;onLeftPaneWidthChange:(width:number)=>void;themePreference:ThemePreference;onThemePreferenceChange:(value:ThemePreference)=>void;ai:AiSettingsController;plugins:PluginSettingsController}){
  return <div className={styles.root} data-ui="settings-surface"><SettingsPage activeSection={activeSection} onSectionChange={onSectionChange} onClose={onClose} leftPaneWidth={leftPaneWidth} onLeftPaneWidthChange={onLeftPaneWidthChange} themePreference={themePreference} onThemePreferenceChange={onThemePreferenceChange} aiProviders={ai.providerViews} selectedAiProviderId={ai.selectedProviderId} onSelectAiProvider={ai.setSelectedProviderId} aiAccounts={ai.accounts} activeAiModel={ai.snapshot.activeModel} aiSecretPersistence={ai.hostAvailable?ai.snapshot.secretPersistence:"unavailable"} aiHostAvailable={ai.hostAvailable} onProbeAiAccount={ai.probe} onSaveAiAccount={ai.save} onConnectAiSubscription={ai.connectSubscription} onReprobeAiAccount={ai.reprobe} onDeleteAiAccount={ai.deleteAccount} onSelectAiAccountModel={ai.selectAccountModel} onActivateAiAccountModel={ai.activateAccountModel} pluginSettings={{hostAvailable:plugins.hostAvailable,registryGeneration:plugins.snapshot.registry.generation,installed:plugins.installed,onInspectPlugin:plugins.inspect,onInstallPlugin:plugins.install,onSetPluginEnabled:plugins.setEnabled,onRemovePlugin:plugins.remove,onCancelPlugin:plugins.cancel}}/></div>;
}
